rootProject.name = "Adyeshach"

include("plugin")
include("project:common")
include("project:common-impl")
include("project:common-impl-packetevents")
include("project:module-bukkit")
include("project:compat-beton-quest")
include("project:compat-germ-engine")
include("project:compat-model-engine-v2")
include("project:compat-model-engine-v4")
include("project:compat-better-model")
include("project:module-editor")
include("project:module-language")
include("project:module-legacy-api")
